set -s set-clipboard external
set -s escape-time 0
set -s focus-events on

set -g history-limit 10000
set -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g status-interval 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind s
bind s choose-tree -sZ -O name

unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode-vi Space
bind -T copy-mode-vi v send -X begin-selection
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi y send -X copy-pipe-and-cancel

set -g @bg '#181825'
set -g @text '#cdd6f4'
set -g @overlay0 '#6c7086'
set -g @overlay2 '#9399b2'
set -g @lavender '#b4befe'
set -g @base '#1e1e2e'

set -g status-style 'bg=#{@bg},fg=#{@text}'
set -g message-style 'bg=#{@bg},fg=#{@text}'
set -g mode-style 'bg=#{@text},fg=#{@base}'

set -g window-status-style 'bg=#{@bg},fg=#{@overlay2}'
set -g window-status-current-style 'bg=#{@bg},fg=#{@text}'

set -g pane-active-border-style 'fg=#{@lavender}'
set -g pane-border-style 'fg=#{@overlay0}'
