set -g default-shell /usr/bin/zsh

set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty*:RGB"

set -g set-clipboard on
set -g detach-on-destroy off
set -s escape-time 0
set -g history-limit 10000
set -g focus-events on
set -g mode-keys vi
set -g mouse on
set -g status-interval 1

unbind C-b
set -g prefix C-a

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf \; display "Config reloaded..."
unbind s
bind s choose-tree -sZ -O name

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -T copy-mode-vi 'v' send -X begin-selection 
bind -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-position bottom

set -g @bg "#181825"
set -g @fg "#6c7086"
set -g @text "#cdd6f4"
set -g @base "#1e1e2e"
set -g @lavender "#b4befe"
set -g @mauve "#cba6f7"
set -g @red "#f38ba8"

set -g status-right ""

set -gF status-style "bg=#{@bg},fg=#{@fg}"
set -gF message-style "bg=#{@bg},fg=#{@red}"

set -gF window-status-format "#[bg=#{@fg},fg=#{@text}] ##I:##W "
set -gF window-status-current-format "#[bg=#{@mauve},fg=#{@base}] ##I:##W "

set -g pane-active-border-style "fg=#{@lavender}"
set -g pane-border-style "fg=#{@fg}"
