#! /bin/sh

#---------- Autostart ----------#
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh
firefox &

#---------- Wallpaper ----------#
feh --no-fehbg --bg-fill ~/.wallpaper/1.png

#---------- Workspaces ---------#
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7

#---------- Gaps ----------#
bspc config gapless_monocle true
bspc config window_gap           8

#---------- Borders ----------#
bspc config borderless_monocle true
bspc config border_width         2

#---------- Colors ----------#
bspc config normal_border_color "#2f334d"
bspc config focused_border_color "#82aaff"
bspc config active_border_color "#000000"
bspc config presel_feedback_color "#82aaff"

#---------- Other Settings ----------#
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 74.97
bspc config split_ratio          0.52
bspc config pointer_modifier	super

#---------- Rules ----------#
bspc rule -a firefox desktop='^2'
