[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
live_config_reload = true

[selection]
save_to_clipboard = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_title = true
dynamic_padding = true
padding = { x = 4, y = 4 }
class = { instance = "Alacritty", general = "Alacritty" }

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    {key = "y", mods = "Control", action = "Copy"},
    {key = "p", mods = "Control", action = "Paste"}
]
